name: Deploy to S3

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        npm install
        npm run generate

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sync to S3
      run: |
        if [ "${{ github.ref_name }}" == "main" ]; then
          BUCKET_NAME=${{ secrets.S3_BUCKET_MAIN }}
        elif [ "${{ github.ref_name }}" == "dev" ]; then
          BUCKET_NAME=${{ secrets.S3_BUCKET_DEV }}
        else
          echo "Branch not configured for deployment"
          exit 1
        fi

        aws s3 sync .output/public s3://$BUCKET_NAME --delete